server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://gitlab-cts.stackroute.in/Sudhir.EkanathBhoite/usecase-config
          username: Sudhir.EkanathBhoite@cognizant.com
          password: P@ssw0rd
          clone-on-start: true