server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: 
          username: 
          password:
          clone-on-start: true