server:
  port: 8084


spring:
  application:
    name: API-GATEWAY

  main:
    web-application-type: reactive


  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/v1/**


        - id: news-api
          uri: http://localhost:8090
          predicates:
            - Path=/search/**

        - id: wishlist-service
          uri: http://localhost:8585
          predicates:
            - Path=/api/news/**

  config:
    import: optional:configserver:http://localhost:8085

